app:
  name: "bluebell"
  version: "0.0.1"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  file_name: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "411122"
  db_name: "bluebell_db"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100